version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: .
    container_name: server
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb?schema=public
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && node dist/index.js"

volumes:
  pgdata: