export class UserDto {
    name: string;
    email: string;
    password: string;
    cvu: number | undefined;

    // User DTOs do not necesarily store a CVU as at the time of creation the CVU is generated by the UserService

    constructor(name: string, email: string, password: string, cvu: number = undefined) {
        this.name = name;
        this.email = email;
        this.password = password;
        this.cvu = cvu;
    }
}